name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  firebase_database: ^12.0.3
  firebase_storage: ^13.0.3
  cloud_firestore: ^6.0.3
  flutter_slider_drawer: ^3.0.2
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  
flutter_icons:
  android: true
  ios: true
  image_path: 'lib/assets/favicon.png'

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
    - lib/assets/logo1.png
    - lib/assets/favicon.png
    - lib/assets/landing_page.png
